let recognition;
let isRecording = false;
let finalTranscript = "";


/* =========================
   TEXT INPUT
========================= */

function generateFromText() {

    const lesson =
        document.getElementById("lessonInput").value.trim();

    if (lesson === "") {

        alert("Please paste your lesson first.");

        return;
    }

    generateStudyMaterial(lesson);
}


/* =========================
   SPEECH RECOGNITION
========================= */

function setupSpeechRecognition() {

    const SpeechRecognition =
        window.SpeechRecognition ||
        window.webkitSpeechRecognition;

    if (!SpeechRecognition) {

        alert(
            "Speech recognition is not supported in this browser. Try Google Chrome."
        );

        return false;
    }

    recognition = new SpeechRecognition();

    recognition.continuous = true;

    recognition.interimResults = true;

    recognition.lang = "en-US";


    recognition.onresult = function(event) {

        let interimTranscript = "";

        for (
            let i = event.resultIndex;
            i < event.results.length;
            i++
        ) {

            const transcript =
                event.results[i][0].transcript;

            if (event.results[i].isFinal) {

                finalTranscript += transcript + " ";

            } else {

                interimTranscript += transcript;

            }

        }


        document.getElementById("transcript").innerText =
            finalTranscript + interimTranscript;

    };


    recognition.onerror = function(event) {

        console.log("Speech recognition error:", event.error);

    };


    recognition.onend = function() {

        if (isRecording) {

            recognition.start();

        }

    };

    return true;
}


/* =========================
   START / STOP RECORDING
========================= */

function toggleRecording() {

    if (!recognition) {

        const ready =
            setupSpeechRecognition();

        if (!ready) {
            return;
        }

    }


    const button =
        document.getElementById("recordButton");

    const status =
        document.getElementById("recordingStatus");


    if (!isRecording) {

        finalTranscript = "";

        document.getElementById("transcript").innerText =
            "Listening...";


        recognition.start();

        isRecording = true;

        button.innerText =
            "⏹️ Stop Recording";

        status.innerText =
            "🔴 Recording class...";

    } else {

        recognition.stop();

        isRecording = false;

        button.innerText =
            "🎙️ Start Recording";

        status.innerText =
            "Recording stopped.";

    }

}


/* =========================
   GENERATE FROM AUDIO
========================= */

function generateFromAudio() {

    const transcript =
        finalTranscript.trim();


    if (transcript === "") {

        alert(
            "Record some audio before generating study material."
        );

        return;
    }


    generateStudyMaterial(transcript);

}


/* =========================
   STUDY MATERIAL
========================= */

function generateStudyMaterial(lesson) {

    document
        .getElementById("results")
        .classList.remove("hidden");


    /* NOTES */

    document.getElementById("notesContent").innerHTML = `

        <p>
            <strong>Lesson Content</strong>
        </p>

        <p>
            ${lesson}
        </p>

        <br>

        <p>
            <strong>AI Summary</strong>
        </p>

        <p>
            This lesson has been processed.
            The full AI version will summarize the
            important concepts and remove unnecessary
            information.
        </p>

    `;


    /* QUIZ */

    document.getElementById("quizContent").innerHTML = `

        <p>
            Which statement best describes the
            main idea of the lesson?
        </p>

        <button onclick="answer('A')">
            A. Main concept
        </button>

        <br>

        <button onclick="answer('B')">
            B. Secondary concept
        </button>

        <br>

        <button onclick="answer('C')">
            C. Unrelated concept
        </button>

    `;


    /* FLASHCARDS */

    document.getElementById("flashcardContent").innerHTML = `

        <p>
            <strong>Question</strong>
        </p>

        <p>
            What is an important concept
            from this lesson?
        </p>

        <button onclick="showAnswer()">
            Reveal Answer
        </button>

        <p id="flashAnswer" class="hidden">

            The answer will be generated by AI
            from the lesson transcript.

        </p>

    `;


    document
        .getElementById("results")
        .scrollIntoView({
            behavior: "smooth"
        });

}


/* =========================
   FLASHCARD
========================= */

function showAnswer() {

    document
        .getElementById("flashAnswer")
        .classList.toggle("hidden");

}


/* =========================
   QUIZ
========================= */

function answer(option) {

    alert(
        "You selected option " + option
    );

}


/* =========================
   CHATBOT
========================= */

function askQuestion() {

    const question =
        document
            .getElementById("question")
            .value
            .trim();


    if (question === "") {

        alert("Please enter a question.");

        return;

    }


    document
        .getElementById("chatAnswer")
        .innerHTML = `

        <p>
            <strong>ClassMind AI:</strong>
        </p>

        <p>
            Your question has been received.
            The AI chatbot will answer using
            the content of your lesson.
        </p>

    `;

}
